import fs from "fs";
import path from "path";
import { SKILL_FILENAME } from "../constants/heuristics.js";
import { ensureDir } from "../utils/fs.utils.js";

export interface SkillIndexEntry {
  id: string;
  category: string;
  name: string;
  description: string;
}

/**
 * Loads the pre-built skills_index.json that ships alongside bundled-skills.
 * This index is generated by the upstream Antigravity repo (generate_index.py)
 * and downloaded during the sync-skills build step.
 *
 * Falls back to an empty array if the file is missing so the plugin degrades
 * gracefully without crashing OpenCode.
 */
export function loadSkillsIndex(bundledSkillsPath: string): SkillIndexEntry[] {
  const indexPath = path.join(bundledSkillsPath, "skills_index.json");
  if (!fs.existsSync(indexPath)) return [];
  try {
    const raw = fs.readFileSync(indexPath, "utf-8");
    return JSON.parse(raw) as SkillIndexEntry[];
  } catch {
    return [];
  }
}

/**
 * Copies every skill folder from bundledSkillsPath directly into
 * the vault under the appropriate category sub-directory.
 *
 * Category is resolved from skills_index.json (upstream-generated),
 * not from TypeScript keyword heuristics, so it stays accurate as
 * the skill collection grows.
 *
 * The activeSkillsDir is never used as a staging area — user custom
 * skills already present there are never moved or overwritten.
 */
export function installSkillsToVault(
  bundledSkillsPath: string,
  vaultDir: string,
  index: SkillIndexEntry[]
): void {
  if (!fs.existsSync(bundledSkillsPath)) return;

  // Build O(1) lookup: skill folder name → category
  const categoryMap = new Map(index.map((e) => [e.id, e.category ?? "_uncategorized"]));

  for (const entry of fs.readdirSync(bundledSkillsPath)) {
    // Skip hidden files, the index file itself, and non-directories
    if (entry.startsWith(".") || entry === "skills_index.json" || entry === "README.md") continue;
    const srcPath = path.join(bundledSkillsPath, entry);
    if (!fs.statSync(srcPath).isDirectory()) continue;

    const category = categoryMap.get(entry) ?? "_uncategorized";
    const destPath = path.join(vaultDir, category, entry);

    ensureDir(path.join(vaultDir, category));
    fs.cpSync(srcPath, destPath, { recursive: true, force: true });
  }
}
