name: Issue assignment

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Numero della issue da assegnare'
        required: true
        type: number

permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: FrancoStino
          issue-number: ${{ github.event.inputs.issue_number || github.event.issue.number }}
